# Generated by Django 5.2 on 2025-04-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Operations', 'Operations'), ('Debtors', 'Debtors'), ('Creditors', 'Creditors'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Maintenance', 'Maintenance'), ('Admin', 'Admin')], max_length=50),
        ),
    ]
