# Generated by Django 5.2 on 2025-04-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_workinghoursconfig_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('suspended', 'Suspended'), ('on_leave', 'On Leave')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
