# Generated by Django 5.2 on 2025-04-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employee_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('on_leave', 'On Leave'), ('deceased', 'Deceased'), ('retired', 'Retired'), ('maternity_leave', 'Maternity Leave'), ('probation', 'Probation'), ('resigned', 'Resigned')], default='active', max_length=20),
        ),
    ]
