# Generated by Django 5.2 on 2025-04-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.CharField(max_length=9)),
                ('lower_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('base_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('marginal_rate', models.DecimalField(decimal_places=2, help_text='Enter as a percentage, e.g., 18 for 18%', max_digits=5)),
            ],
            options={
                'ordering': ['tax_year', 'lower_limit'],
            },
        ),
    ]
