# Generated by Django 5.2 on 2025-04-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_seed_tax_brackets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='gross_income',
            new_name='basic_salary',
        ),
    ]
