# Generated by Django 5.2 on 2025-04-24 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payslip_gross_income_alter_payslip_basic_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='worked_hours',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.workedhours'),
        ),
    ]
