# Generated by Django 5.2 on 2025-04-26 11:52

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_payslip_worked_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Annual', 'Annual Leave'), ('Sick', 'Sick Leave'), ('Family', 'Family Responsibility Leave'), ('Maternity', 'Maternity Leave'), ('Parental', 'Parental Leave'), ('Study', 'Study Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('expected_birth_date', models.DateField(blank=True, null=True)),
                ('actual_birth_date', models.DateField(blank=True, null=True)),
                ('documentation_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='payroll.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Annual', 'Annual Leave'), ('Sick', 'Sick Leave'), ('Family', 'Family Responsibility Leave'), ('Maternity', 'Maternity Leave'), ('Parental', 'Parental Leave'), ('Study', 'Study Leave')], max_length=20)),
                ('total_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cycle_start', models.DateField(default=datetime.date.today)),
                ('related_event_date', models.DateField(blank=True, null=True)),
                ('documentation_submitted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'unique_together': {('employee', 'leave_type')},
            },
        ),
    ]
